kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
  image: kindest/node:v1.31.2

- role: worker
  image: kindest/node:v1.31.2

- role: worker
  image: kindest/node:v1.31.2
  extraPortMappings:
    - containerPort: 7000
      hostPort: 7000
      protocol: TCP
    - containerPort: 7001
      hostPort: 7001
      protocol: TCP
     - containerPort: 7002
      hostPort: 7002
      protocol: TCP


